disable MSBuild server (concurrency) for DotNETNativeBuilder
As of .NET 11 SDK RC 1, running concurrent `dotnet publish` for iOS/macOS/simulator/etc
often results in runtime errors similar to:

> System.Exception: The Command "/usr/local/share/dotnet/dotnet publish -r iossimulator-x64 -v normal" in directory "buildTmp/BeyondNETBuilderDotNETNativeBuilder_BeyondDotNETSampleKit__iOSSimulator_X64jnyHum" exited with exit code 0
> System.Exception: MSBuild server unavailable: could not connect to the server within the timeout window; the server may have failed to start. Falling back to an in-process build.

Workaround these (hopefully temporarily!) issues by disabling MSBuild server during native publishing.

ref. https://learn.microsoft.com/visualstudio/msbuild/msbuild-server#shut-down-or-disable-msbuild-server